# Generated by Django 6.0.3 on 2026-05-14 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('kpis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluationdetail',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='evaluations.evaluation'),
        ),
        migrations.AddField(
            model_name='evaluationdetail',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_details', to='kpis.kpi'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationdetail',
            unique_together={('evaluation', 'kpi')},
        ),
    ]
