# Generated by Django 6.0.3 on 2026-05-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_contract', models.CharField(choices=[('CONTRACTOR', 'Contractor'), ('SUPERVISOR', 'Supervisor')], max_length=20)),
                ('responsibility', models.CharField(blank=True, max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['contract__title', 'role_in_contract', 'user__full_name'],
            },
        ),
    ]
