# Generated by Django 6.0.3 on 2026-05-14 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'end_date'], name='contracts_c_status_537325_idx'),
        ),
    ]
