# Generated by Django 6.0.3 on 2026-05-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('PERFORMANCE', 'Performance Report'), ('CONTRACT_SUMMARY', 'Contract Summary'), ('EVALUATION_ANALYTICS', 'Evaluation Analytics')], max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='contracts.contract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
